name: Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Determine the target branch (blue / green)
        id: target-branch
        env:
          GH_PAGES: true
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          # Determine the current branch (blue or green)
          current_branch=$(curl -L "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACTIONS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/pages | jq -r .source.branch)
          echo $current_branch
          if [ "$current_branch" = "gh-pages-blue" ]; then
            echo "green"
            target_branch="gh-pages-green"
          else
            echo "blue"
            target_branch="gh-pages-blue"
          fi

           echo "TARGET_BRANCH=$target_branch" >> $GITHUB_OUTPUT

      - name: Deploy to GitHub Pages
        env:
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          TARGET_BRANCH: ${{ steps.target-branch.outputs.TARGET_BRANCH }}
          GH_PAGES: true
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          npm ci
          npm run build
          git add .
          git commit -m 'Update GitHub Pages'
          git pull --rebase --strategy=ours origin $TARGET_BRANCH
          git subtree push --prefix dist origin $TARGET_BRANCH

          echo $TARGET_BRANCH
          # Set GitHub Pages source
          curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACTIONS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/pages -d '{"source":{"branch": "'"$TARGET_BRANCH"'","path":"/"}}'
