name: Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Determine the target branch (blue / green)
        env:
          GH_PAGES: true
        run: |
          # Determine the current branch (blue or green)
          current_branch=$(curl -s -H "Authorization: token $ACTIONS_TOKEN" https://api.github.com/repos/${{ github.repository }}/pages | jq -r .source.branch)
          echo $current_branch
          if [ "$current_branch" = "gh-pages-blue" ]; then
            echo "green"
            target_branch="gh-pages-green"
          else
            echo "blue"
            target_branch="gh-pages-blue"
          fi

      - name: Deploy to GitHub Pages
        env:
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          TARGET_BRANCH: $target_branch
        run: |
          npm run gh-pages

      - name: Update GitHub Pages source branch
        env:
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          curl -s -X PATCH -H "Authorization: token $ACTIONS_TOKEN" -d '{"source": {"branch": "'"$target_branch"'"}}' https://api.github.com/repos/${{ github.repository }}/pages

          