name: Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12

    - name: Install dependencies and build the app
      run: |
        npm ci
        GH_PAGES=true npm run build

    - name: Blue-green deployment
      run: |
        CURRENT_BRANCH=$(curl -s -H "Accept: application/vnd.github+json" https://api.github.com/repos/$GITHUB_REPOSITORY/pages | jq -r '.source.branch')
        if [ "$CURRENT_BRANCH" == "gh-pages-blue" ]; then
          NEW_BRANCH="gh-pages-green"
        else
          NEW_BRANCH="gh-pages-blue"
        fi

        git config user.name "GitHub Action"
        git config user.email "github-action@users.noreply.github.com"
        git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"

        # Create a temporary branch and move the built app to the root of the new branch
        git checkout --orphan temp_$NEW_BRANCH
        git rm --cached -r .
        cp -r dist/* .
        rm -rf dist

        # Commit and push the changes to the new branch
        git add .
        git commit -m "Update GitHub Pages"
        git push origin temp_$NEW_BRANCH:$NEW_BRANCH

        # Switch back to the original branch and delete the temporary branch
        git checkout -f $GITHUB_REF
        git branch -D temp_$NEW_BRANCH

    - name: Update GitHub Pages branch
      run: |
        curl -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/pages \
          -d "{\"source\": {\"branch\": \"$NEW_BRANCH\", \"path\": \"/\"}}"
