name: Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Deploy to GitHub Pages
        env:
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          GH_PAGES: true
        run: |
          # Determine the current environment branch
          current_branch=$(curl -L "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACTIONS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/pages | jq -r .source.branch)
          
          # Determine the target environment branch
          if [ "$current_branch" = "gh-pages-blue" ]; then
            echo "green"
            target_branch="gh-pages-green"
          else
            echo "blue"
            target_branch="gh-pages-blue"
          fi

          # Report back
          echo The static site is current deployed to $current_branch.
          echo Targeting $target_branch for the deployment.

          # Configure the user and email for the commit
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          # Delete the current target branch
          request_status=curl -s -o /dev/null -w "%{http_code}" -X DELETE -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$target_branch

          # Perform a clean install of dependencies
          npm ci

          # Build the application for production
          npm run build

          # Commit the code and push to the target branch
          git add .
          git commit -m 'Deploy the GitHub Pages site to the $target_branch branch'
          git subtree push --prefix dist origin $target_branch

          echo $target_branch
          # Set GitHub Pages source
          curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACTIONS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/pages -d '{"source":{"branch": "'"$target_branch"'","path":"/"}}'
